services:
  cs2:
    image: joedwards32/cs2
    container_name: cs2
    restart: unless-stopped
    network_mode: host  # MUDANÇA: Use host network para evitar problemas de NAT
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # Server configuration
      - SRCDS_TOKEN=BA4146AA62D17BB88F145BB7D3934479
      - STEAMAPPVALIDATE=0
      - CS2_SERVERNAME=MIX 5v5 !ws só os noia online!!!
      - CS2_CHEATS=0
      - CS2_PORT=27015
      - CS2_SERVER_HIBERNATE=0
      - CS2_LAN=0
      - CS2_RCONPW=drogas
      - CS2_PW=
      - CS2_MAXPLAYERS=12
      # MUDANÇA: Argumentos simplificados
      - CS2_ADDITIONAL_ARGS="-ip 0.0.0.0 +net_public_adr rebolandolentinho.ddns.net +net_steamcnx_allowrelay 1"
      # Game modes
      - CS2_GAMEALIAS=competitive
      - CS2_GAMETYPE=0
      - CS2_GAMEMODE=1
      - CS2_MAPGROUP=mg_active
      - CS2_STARTMAP=de_ancient
      # Workshop Maps
      - CS2_HOST_WORKSHOP_COLLECTION=
      - CS2_HOST_WORKSHOP_MAP=
      # Bots
      - CS2_BOT_DIFFICULTY=3
      - CS2_BOT_QUOTA=0
      - CS2_BOT_QUOTA_MODE=competitive
      # TV
      - TV_AUTORECORD=0
      - TV_ENABLE=0
      - TV_PORT=27020
      - TV_PW=drogas
      - TV_RELAY_PW=drogas
      - TV_MAXRATE=0
      - TV_DELAY=120
      # Logs
      - CS2_LOG=off
      - CS2_LOG_MONEY=0
      - CS2_LOG_DETAIL=0
      - CS2_LOG_ITEMS=0
    volumes:
      - ./data-server/:/home/steam/cs2-dedicated/
    # Recursos do sistema
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    stdin_open: true
    tty: true
